### ISSUE TITLE
What is the difference between SME Server & nethserver

### ISSUE THREAD

**Issue by topstarnetwork** [nethesis/nethserver-release#1]
Hello,
What is the difference between SME Server & nethserver
Would you have a comparison table?
Regards, Heather

**Comment by gsanchietti** [comment]
Hi, you can checkout this blog post: http://www.nethserver.org/nethserver_smeserver/

Feel free to ask further information!

Il 31 gennaio 2015 12:08:14 CET, Heather Raffaella Riverso <notifications@github.com> ha scritto:
>Hello,
>What is the difference between SME Server & nethserver
>Would you have a comparison table?
>Regards, Heather
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/nethesis/nethserver-release/issues/1

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by topstarnetwork** [comment]
Thanks for your response,
as I am not a IT literate could you tell me then if nethserver is superiour to SME Server?
As I am looking for the most scalable, extendable enterprise open source server I don't know wich one from both to choose for my next project.
As I said I am not a system admin neather software developer,
regards, Heather

**Comment by gsanchietti** [comment]
Hi,
SME and NethServer are a little bit different now.
There isn't one better than the other.

Maybe if you list your requirements, like a list of modules you need, I can suggest you the best choice.


Il 01 febbraio 2015 01:17:08 CET, Heather Raffaella Riverso <notifications@github.com> ha scritto:
>Thanks for your response,
>as I am not a IT literate could you tell me then if nethserver is
>superiour to SME Server?
>As I am looking for the most scalable, extendable enterprise open
>source server I don't know wich one from both to choose for my next
>project.
>As I said I am not a system admin neather software developer,
>regards, Heather
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/nethesis/nethserver-release/issues/1#issuecomment-72344234

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by topstarnetwork** [comment]
My main concern is not more a module issue but an enterprise  performance, scalability of the server (adding and creating  new addons easyly) and best code compliance is concerned,
regards, Heather

**Comment by filippocarletti** [comment]
NethServer is totally compliant to CentOS "rules", while SME Server is not.
As an example, NethServer uses the original unmodified CentOS installer, so
that if a system supports CentOS it will equally support NethServer.
Performance will be the same of CentOS.
Adding software to NethServer is far easier and faster than adding it to
SME, because linux software run on NethServer as if it is a CentOS, while
SME server always demand that software is adjusted to follow SME rules
(i.e. runit, supervised, runlevel, etc).
I added many features to SME in the last 15 years, but now working on
NethServer is a breeze, I blindly follow CentOS howto and it usually works
out of the box. If I have a problem, usually google has the answer (because
NethServer uses common software and configuration, often other have
encountered and solved a problem before me).

Disclaimer: I was a SME developer and I forked it into NethServer.



On Mon, Feb 2, 2015 at 12:56 PM, Heather Raffaella Riverso <
notifications@github.com> wrote:

> My main concern is not more a module issue but an enterprise performance,
> scalability of the server (adding and creating new addons easyly) and best
> code compliance is concerned,
> regards, Heather
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nethesis/nethserver-release/issues/1#issuecomment-72445074>
> .
>



-- 
Ciao,
Filippo

**Comment by topstarnetwork** [comment]
I read all your bio, congratulation you are a great coder.
Your answers convinced me, this is all I wanted to know,
I will use NethServer for some of my comming project.
Just a last question,
is it possible to have on NethServer. some kind of hosting control panel to host differnet domain name websites and if so is it possible to allocate for each site a diferent ip while being hosted on NethServer?
A cpanel or webmin style would be great in order for the website owner to login to his control hosting control panel,
regards, Heather

**Comment by filippocarletti** [comment]
>
> is it possible to have on NethServer. some kind of hosting control panel
> to host differnet domain name websites and if so is it possible to allocate
> for each site a diferent ip while being hosted on NethServer?
> A cpanel or webmin style would be great in order for the website owner to
> login to his control hosting control panel,
> regards, Heather
>

It *is* possible to host multiple website on different IPs, BUT NethServer
was planned as a system for a single company. This usually means that there
are no interfaces to facilitate hosting environments like cpanel. The idea
behind multiple domain is that a single company often has multiple websites
(maybe in different languages) and want them hosted on a single server.

I understand the idea of extending NethServer towards domain hosting, I
have talked about that in the past with other users and I even filed some
issues on dev.nethserver.org to implement something like an "hosting
add-on".
Today, I will not use NethServer as an hosting platform for hundreds of
customers (tens could be viable).

However, since I'd like to extend NethServer options, I'd like to receive
comments on a potential add-on.
Could we work together on this?


-- 
Ciao,
Filippo

**Comment by DavidePrincipi** [comment]
The expected approach is dropping  `.conf` files under `/etc/httpd/conf.d`. I think as far as the control panel follows this rule, there would not be big issues. If this is not acceptable, it is still possible to tweak httpd.conf itself through the [template system](http://docs.nethserver.org/projects/nethserver-devel/en/latest/templates.html#templates).

**Comment by filippocarletti** [comment]
>
> The expected approach is dropping .conf files under /etc/httpd/conf.d. I
> think as far as the control panel follows this rule, there would not be big
> issues. If this is not acceptable, it is still possible to tweak httpd.conf
> itself through the template system
> <http://docs.nethserver.org/projects/nethserver-devel/en/latest/templates.html#templates>
> .
>
>
Does this mean  that we could find an existing cpanel-like system that
works on NethServer out-of-the-box or after minor customization?


-- 
Ciao,
Filippo

**Comment by DavidePrincipi** [comment]
On Mon, 2015-02-02 at 06:39 -0800, filippocarletti wrote:
> Does this mean that we could find an existing cpanel-like system that
> works on NethServer out-of-the-box or after minor customization?

I don't really know what are the requirements of a similar software. I
know NethServer is modular, and following the template system
philosophycan install

**Comment by DavidePrincipi** [comment]
[I'm sorry, I sent the message too early]

On Mon, 2015-02-02 at 15:48 +0100, Davide Principi wrote:
> On Mon, 2015-02-02 at 06:39 -0800, filippocarletti wrote:
> > Does this mean that we could find an existing cpanel-like system that
> > works on NethServer out-of-the-box or after minor customization?
> 
> I don't really know what are the requirements of a similar software. I
> know NethServer is modular, and following the template system
> philosophycan install 

...I was saying...

following the template system approach it should be possible to drop in
anything is known to work on CentOS without too much effort.  Of course
how much this is worth depends on how much the module could take
advantage from the other modules, for instance the LDAP server, or mail
stack or whatsoever....

**Comment by topstarnetwork** [comment]
The hosting addon for nethserver would be the greatest idea!
Unfortunatly as I am not a software developer I can not help but it would be great if we could develop a nethserver virtualmin http://www.webmin.com/virtualmin.html and 1 addon for cloudmin http://www.webmin.com/cloudmin.html

As those 2 softwares are written in perl it would be kind of easy to have them on nethserver

**Comment by filippocarletti** [comment]
I looked briefly at both software, they seem interesting but maybe a bit
too "intrusive". However they are a good starting point for new features.
Thank you for having pointed me there.

I'd like you to evaluate webvirtmgr, I think it could be an option to
cloudmin:
http://docs.nethserver.org/en/latest/webvirtmgr.html



On Mon, Feb 2, 2015 at 5:00 PM, Heather Raffaella Riverso <
notifications@github.com> wrote:

> The hosting addon for nethserver would be the greatest idea!
> Unfortunatly as I am not a software developer I can not help but it would
> be great if we could develop a nethserver virtualmin
> http://www.webmin.com/virtualmin.html and 1 addon for cloudmin
> http://www.webmin.com/cloudmin.html
>
> As those 2 softwares are written in perl it would be kind of easy to have
> them on nethserver
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nethesis/nethserver-release/issues/1#issuecomment-72481714>
> .
>



-- 
Ciao,
Filippo

**Comment by topstarnetwork** [comment]
Well we can keep virtualmin  for hosting sites and for vps cloud webvirtmgr is only for kvm so the better will be to use a enterprise one such as xCAT https://github.com/xcat-org wich supports physical and virtual cloud with xen and kvm, this is the best choice!

**Comment by topstarnetwork** [comment]
Hello does NethServer has any http://geronimo.apache.org/ java application server installation addon or should apache geromino be installed on a stand alone linux distro as it seems to be a server itself? http://geronimo.apache.org/GMOxDOC11/installation.html

Thanks.

**Comment by gsanchietti** [comment]
> Hello does NethServer has any http://geronimo.apache.org/ java
> application server installation addon or should apache geromino be
> installed on a stand alone linux distro as it seems to be a server
> itself? http://geronimo.apache.org/GMOxDOC11/installation.html

Hi, you should be able to install following the above documentation.
If you have problems, just let us know.

Please, consider to switch to official channels like IRC or ML.
You can find all available channels here:
http://www.nethserver.org/community/

Giacomo

**Comment by topstarnetwork** [comment]
Hello,
I just found a centos based corporate server with cpanel hosting control pane features as requested by me in the past messages, maybe you can replicate the same code on Nethserver as it is centos based,
here is the link http://www.blueonyx.it/

**Comment by DavidePrincipi** [comment]
On Sat, 2015-02-21 at 06:00 -0800, Heather Raffaella Riverso wrote:
> Hello,
> I just found a centos based corporate server with cpanel hosting
> control pane features as requested by me in the past messages, maybe
> you can replicate the same code on Nethserver as it is centos based,
> here is the link http://www.blueonyx.it/

Looks awesome! I'll try their demo!

-- 
Davide Principi

#davidep | @davideprincipi | GPG 0x5651EA71

**Comment by DavidePrincipi** [comment]
@topstarnetwork, thanks for asking. Please, consider continuing the discussion on
http://community.nethserver.org/t/how-manage-apache-nginx-virtual-hosts/554
